# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy apps to Azure Function App
run-name: Build and deploy Java Function App
on:
  push:
    branches:
      - "features/integrations"
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: "app-dev-fnc-java-integration"
  POM_XML_DIRECTORY: "."
  JAVA_VERSION: "17"
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Configure Azure Credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ARM_CREDENTIALS }}

      - name: "Run az commands"
        run: |
          az account show
          az account set --subscription ${{ env.ARM_SUBSCRIPTION_ID }}
          az configure --defaults location=northeurope

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set variables
        id: setvars
        run: |
          if [[ "${{ github.base_ref }}" == "features/integrations" || "${{ github.ref }}" == "refs/heads/features/integrations" ]]; then
              echo ENV_NAME="dev" >> $GITHUB_ENV
          fi

      - name: "Run mvn"
        shell: bash
        run: |
          # If your function app project is not located in your repository's root
          # Please change your directory for maven build in pushd
          pushd './${{ env.POM_XML_DIRECTORY }}'
          mvn clean package -Dmaven.test.skip=true
          mvn azure-functions:package -Dmaven.test.skip=true
          popd

          # mvn clean package
          # mvn azure-functions:package
          # popd

      - name: Deploy Java function to Azure Function App
        if: github.ref == 'refs/heads/features/integrations' && github.event_name == 'push'
        shell: bash
        run: |
          ls -lh
          cd ./target/azure-functions/emat-${ENV_NAME}-fnc-java-integration/
          zip -r ../app.zip .
          export token=$(az account get-access-token --query "accessToken" -o tsv)
          echo "zip done && token recovered"
          az functionapp deployment source config-zip --name app-${ENV_NAME}-fnc-java-integration --resource-group app-emat-${ENV_NAME} --src ../app.zip
          echo "The deployment of function ${{env. AZURE_FUNCTIONAPP_NAME}} was successful"
